In [2]:
# ================
# PyTorch Setup
# ================

import torch  # The basic PyTorch library 
import torch.nn as nn   # Neural network module
import torch.optim as optim # Optimizers module
import torch.nn.functional as F # for different activation functions

print("PyTorch version:", torch.__version__) # cheack the version of PyTorch

PyTorch version: 2.11.0+cu128


In [3]:
torch.cuda.is_available()

True

In [4]:
#  ===============
# Creatina a Tensor
#  =============== 

# Tensor from a list
x = torch.tensor([1,2,3,4,5])

# Float tensor
y = torch.tensor([1.2, 2.3, 3.4, 4.5, 5.6])

# Matrix 
matrix = torch.tensor([
     [1, 2, 3],
     [4, 5, 6]
])

print("Tensor x:", x)
print("Tensor y:", y)
print("Matrix:\n", matrix)

Tensor x: tensor([1, 2, 3, 4, 5])
Tensor y: tensor([1.2000, 2.3000, 3.4000, 4.5000, 5.6000])
Matrix:
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
# ================
# Tensor Attributes
# ================

x = torch.rand(3, 4)  # Random tensor of shape (3, 4)
print("Tensor x:\n", x)
print("Shape of x:", x.shape)
print("Data type of x:", x.dtype)
print("Device of x:", x.device)

Tensor x:
 tensor([[0.0922, 0.8404, 0.3120, 0.1750],
        [0.0969, 0.4175, 0.6819, 0.1067],
        [0.7806, 0.8007, 0.0760, 0.8199]])
Shape of x: torch.Size([3, 4])
Data type of x: torch.float32
Device of x: cpu


In [6]:
# ===============
# Special Tensors
# ===============

zero_tensor = torch.zeros(2, 3)  # Tensor filled with zeros
one_tensor = torch.ones(2, 3)    # Tensor filled with ones
random_uniform_tensor = torch.rand(2, 3)  # Tensor with random values from uniform distribution
identity_matrix = torch.eye(3)  # Identity matrix of size 3x3

print("Zero Tensor:\n", zero_tensor)
print("One Tensor:\n", one_tensor)
print("Random Uniform Tensor:\n", random_uniform_tensor)
print("Identity Matrix:\n", identity_matrix)


Zero Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
One Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random Uniform Tensor:
 tensor([[0.6921, 0.3849, 0.5391],
        [0.9437, 0.4672, 0.4962]])
Identity Matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [7]:
#  ===============
# indexing and Slicing
#  ===============

x = torch.tensor([1,2,3,4,5]) 

print("Original Tensor x:", x)
# Indexing
print("First element:", x[0])
print("Last element:", x[-1])
print("Slicing (first three elements):", x[:3])
print("Slicing (last two elements):", x[-2:])

Original Tensor x: tensor([1, 2, 3, 4, 5])
First element: tensor(1)
Last element: tensor(5)
Slicing (first three elements): tensor([1, 2, 3])
Slicing (last two elements): tensor([4, 5])


In [8]:
# ===============
# 2D Tensor Indexing and Slicing
# ===============

x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original 2D Tensor x:\n", x)
# Indexing
print("Element at (0, 1):", x[0, 1])
print("First row:", x[0])
print("Second column:", x[:, 1])   


Original 2D Tensor x:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Element at (0, 1): tensor(2)
First row: tensor([1, 2, 3])
Second column: tensor([2, 5, 8])


In [9]:
# ===============
# Tensor Reshaping
# ===============

x = torch.arange(12)  # Tensor with values from 0 to 11

print("Original Tensor x:", x)

y = x.reshape(3, 4)  # Reshape to a 3x4 matrix

print("Reshaped Tensor y (3x4):\n", y)
print("Shape of x: ", x.shape)
print("Shape of y: ", y.shape)

Original Tensor x: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Reshaped Tensor y (3x4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Shape of x:  torch.Size([12])
Shape of y:  torch.Size([3, 4])


In [10]:
x = torch.arange(50).reshape(5, 10)  # Tensor with values from 0 to 49 reshaped to 5x10
print("Original Tensor x:\n", x)

Original Tensor x:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])


In [11]:
torch.flatten(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
# ============================================================
# view() and reshape()
# Both are used to change tensor shape
# reshape() is generally safer
# ============================================================

x = torch.arange(12)

x_view = x.view(3, 4)
x_reshape = x.reshape(3, 4)

print("Using view:")
print(x_view)

print("Using reshape:")
print(x_reshape)

Using view:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Using reshape:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [13]:
# ============================================================
# unsqueeze() adds a dimension
# squeeze() removes dimensions of size 1
# ============================================================

x = torch.tensor([1, 2, 3])

print("Original shape:", x.shape)

x_unsqueezed = x.unsqueeze(0)
print("After unsqueeze(0):", x_unsqueezed.shape)

x_unsqueezed_2 = x.unsqueeze(1)
print("After unsqueeze(1):", x_unsqueezed_2.shape)

x_squeezed = x_unsqueezed.squeeze()
print("After squeeze:", x_squeezed.shape)

Original shape: torch.Size([3])
After unsqueeze(0): torch.Size([1, 3])
After unsqueeze(1): torch.Size([3, 1])
After squeeze: torch.Size([3])


In [14]:
# ============================================================
# permute() changes the order of dimensions
# Important for images
# ============================================================

# Example image tensor: Height x Width x Channels
image_hwc = torch.randn(224, 224, 3)

print("Original image shape HWC:", image_hwc.shape)

# PyTorch CNNs expect: Channels x Height x Width
image_chw = image_hwc.permute(2, 0, 1)

print("After permute to CHW:", image_chw.shape)

Original image shape HWC: torch.Size([224, 224, 3])
After permute to CHW: torch.Size([3, 224, 224])


In [15]:
# ============================================================
# Basic Tensor Operations
# ============================================================

a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([10.0, 20.0, 30.0])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("a squared:", a ** 2)

a + b: tensor([11., 22., 33.])
a - b: tensor([ -9., -18., -27.])
a * b: tensor([10., 40., 90.])
a / b: tensor([0.1000, 0.1000, 0.1000])
a squared: tensor([1., 4., 9.])


In [16]:
# ============================================================
# Matrix Multiplication
# ============================================================

A = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

B = torch.tensor([
    [5.0, 6.0],
    [7.0, 8.0]
])

C = A @ B

print("A:")
print(A)

print("B:")
print(B)

print("A @ B:")
print(C)

A:
tensor([[1., 2.],
        [3., 4.]])
B:
tensor([[5., 6.],
        [7., 8.]])
A @ B:
tensor([[19., 22.],
        [43., 50.]])


In [17]:
# ============================================================
# Moving Tensor to GPU
# ============================================================

x = torch.randn(3, 4)

print("Before moving:", x.device)

# 1. Define the device (uses GPU if available, otherwise CPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 2. Move your data (your existing code)
x = x.to(device) # or x = x.cuda() if torch.cuda.is_available() else x.cpu()

print("After moving:", x.device)


Before moving: cpu
After moving: cuda:0


In [18]:
# ============================================================
# Autograd
# PyTorch automatically calculates gradients
# ============================================================

x = torch.tensor(2.0, requires_grad=True) # Taking the initial value of x as 2.0 and enabling gradient tracking

y = x ** 2 + 3 * x + 1

print("y:", y)

# Compute dy/dx
y.backward()

print("Gradient dy/dx at x=2:", x.grad)

y: tensor(11., grad_fn=<AddBackward0>)
Gradient dy/dx at x=2: tensor(7.)


In [19]:

# ============================================================
# Autograd with Vectors
# ============================================================

x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

y = x ** 2

loss = y.mean()

print("y:", y)
print("loss:", loss)

loss.backward()

print("Gradient:", x.grad)

y: tensor([1., 4., 9.], grad_fn=<PowBackward0>)
loss: tensor(4.6667, grad_fn=<MeanBackward0>)
Gradient: tensor([0.6667, 1.3333, 2.0000])


In [20]:
# ============================================================
# Manual Linear Regression with Autograd
# y = wx + b
# ============================================================

x = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y_true = torch.tensor([[3.0], [5.0], [7.0], [9.0]])

w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

learning_rate = 0.01

for epoch in range(100):

    y_pred = x * w + b

    loss = torch.mean((y_pred - y_true) ** 2) # The mean squared error loss

    loss.backward()

    with torch.no_grad(): # Temporarily disable gradient computation
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

        w.grad.zero_() # Clear the gradients for the next iteration
        b.grad.zero_() # Clear the gradients for the next iteration

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

print("Learned weight:", w.item())
print("Learned bias:", b.item())

Epoch 0, Loss: 134.8872
Epoch 10, Loss: 3.6459
Epoch 20, Loss: 0.2413
Epoch 30, Loss: 0.1447
Epoch 40, Loss: 0.1341
Epoch 50, Loss: 0.1262
Epoch 60, Loss: 0.1189
Epoch 70, Loss: 0.1120
Epoch 80, Loss: 0.1055
Epoch 90, Loss: 0.0993
Learned weight: 1.7454677820205688
Learned bias: 1.748355507850647


In [21]:
# ============================================================
# nn.Module
# All PyTorch neural networks are written using nn.Module
# ============================================================

class LinearRegressionModel(nn.Module):

    def __init__(self):
        super().__init__()

        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        output = self.linear(x)
        return output

model = LinearRegressionModel()

print(model)

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)


In [22]:
# ============================================================
# Training nn.Module Model
# ============================================================

x = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y_true = torch.tensor([[3.0], [5.0], [7.0], [9.0]])

model = LinearRegressionModel()

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

for epoch in range(100):

    y_pred = model(x)

    loss = criterion(y_pred, y_true)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 35.7666
Epoch 10, Loss: 0.9525
Epoch 20, Loss: 0.0502
Epoch 30, Loss: 0.0254
Epoch 40, Loss: 0.0233
Epoch 50, Loss: 0.0220
Epoch 60, Loss: 0.0207
Epoch 70, Loss: 0.0195
Epoch 80, Loss: 0.0184
Epoch 90, Loss: 0.0173


In [23]:
# ============================================================
# Inspect Model Parameters
# ============================================================

for name, parameter in model.named_parameters():
    print(name)
    print(parameter.data)

linear.weight
tensor([[1.8938]])
linear.bias
tensor([1.3122])


In [34]:
# ============================================================
# Linear Layer
# Input shape: batch_size x input_features
# Output shape: batch_size x output_features
# ============================================================

linear_layer = nn.Linear(in_features=4, out_features=3)

x = torch.randn(5, 4)

output = linear_layer(x)

print("Input shape:", x.shape)
print("Output shape:", output.shape)

Input shape: torch.Size([5, 4])
Output shape: torch.Size([5, 3])


In [35]:
for name, parameter in linear_layer.named_parameters():
    print(name, parameter.shape)

weight torch.Size([3, 4])
bias torch.Size([3])


In [25]:
# ============================================================
# Activation Functions
# ============================================================

x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])

relu_output = F.relu(x)
sigmoid_output = torch.sigmoid(x)
tanh_output = torch.tanh(x)

print("Input:", x)
print("ReLU:", relu_output)
print("Sigmoid:", sigmoid_output)
print("Tanh:", tanh_output)

Input: tensor([-2., -1.,  0.,  1.,  2.])
ReLU: tensor([0., 0., 0., 1., 2.])
Sigmoid: tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808])
Tanh: tensor([-0.9640, -0.7616,  0.0000,  0.7616,  0.9640])


In [26]:
# ============================================================
# Softmax
# Converts logits into probabilities
# ============================================================

logits = torch.tensor([[2.0, 1.0, 0.1]])

probabilities = F.softmax(logits, dim=1)

print("Logits:", logits)
print("Probabilities:", probabilities)
print("Sum:", probabilities.sum())

Logits: tensor([[2.0000, 1.0000, 0.1000]])
Probabilities: tensor([[0.6590, 0.2424, 0.0986]])
Sum: tensor(1.0000)


In [27]:
# ============================================================
# CrossEntropyLoss
# Important:
# It expects raw logits, not softmax probabilities
# ============================================================

logits = torch.tensor([
    [2.0, 1.0, 0.1],
    [0.5, 2.5, 0.3]
])

targets = torch.tensor([0, 1])

criterion = nn.CrossEntropyLoss()

loss = criterion(logits, targets)

print("Loss:", loss.item())

Loss: 0.31853973865509033


In [ ]:
# ============================================================
# Custom Dataset
# ============================================================

from torch.utils.data import Dataset, DataLoader

class SimpleDataset(Dataset):

    def __init__(self):
        self.X = torch.randn(100, 2)
        self.y = (self.X[:, 0] + self.X[:, 1] > 0).long() # using long() to convert boolean to integer labels (0 or 1)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):
        return self.X[index], self.y[index]

dataset = SimpleDataset()

print("Number of samples:", len(dataset))

sample_x, sample_y = dataset[0]

print("Sample input:", sample_x)
print("Sample label:", sample_y)

Number of samples: 100
Sample input: tensor([-0.3867,  1.2591])
Sample label: tensor(1)


In [ ]:
# ============================================================
# DataLoader
# ============================================================

dataloader = DataLoader(
    dataset,
    batch_size=16,
    shuffle=True # shuffel is 'True' because we don't want same order of data set in each batch
)

for batch_x, batch_y in dataloader:
    print("Batch input shape:", batch_x.shape)
    print("Batch label shape:", batch_y.shape)
    break

Batch input shape: torch.Size([16, 2])
Batch label shape: torch.Size([16])


In [30]:
# ============================================================
# MLP for Binary Classification
# ============================================================

class MLP(nn.Module):

    def __init__(self, input_dim, hidden_dim, num_classes):
        super().__init__()

        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)

        x = self.fc2(x)
        x = F.relu(x)

        x = self.fc3(x)

        return x

model = MLP(input_dim=2, hidden_dim=32, num_classes=2).to(device)

print(model)

MLP(
  (fc1): Linear(in_features=2, out_features=32, bias=True)
  (fc2): Linear(in_features=32, out_features=32, bias=True)
  (fc3): Linear(in_features=32, out_features=2, bias=True)
)


In [31]:
# ============================================================
# Training MLP
# ============================================================

dataset = SimpleDataset()

dataloader = DataLoader(
    dataset,
    batch_size=16,
    shuffle=True
)

model = MLP(input_dim=2, hidden_dim=32, num_classes=2).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 20

for epoch in range(epochs):

    model.train()

    total_loss = 0
    correct = 0
    total = 0

    for batch_x, batch_y in dataloader:

        batch_x = batch_x.to(device)
        batch_y = batch_y.to(device)

        logits = model(batch_x)

        loss = criterion(logits, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        predictions = torch.argmax(logits, dim=1)
        correct += (predictions == batch_y).sum().item()
        total += batch_y.size(0)

    accuracy = correct / total

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}, Accuracy: {accuracy:.4f}")

Epoch 1, Loss: 4.5437, Accuracy: 0.6900
Epoch 2, Loss: 4.4122, Accuracy: 0.7900
Epoch 3, Loss: 4.2432, Accuracy: 0.8500
Epoch 4, Loss: 4.0554, Accuracy: 0.9000
Epoch 5, Loss: 3.9196, Accuracy: 0.9000
Epoch 6, Loss: 3.6650, Accuracy: 0.9200
Epoch 7, Loss: 3.4249, Accuracy: 0.9300
Epoch 8, Loss: 3.1548, Accuracy: 0.9400
Epoch 9, Loss: 2.8299, Accuracy: 0.9500
Epoch 10, Loss: 2.7284, Accuracy: 0.9600
Epoch 11, Loss: 2.4985, Accuracy: 0.9600
Epoch 12, Loss: 2.2449, Accuracy: 0.9800
Epoch 13, Loss: 1.9511, Accuracy: 0.9800
Epoch 14, Loss: 1.7607, Accuracy: 0.9800
Epoch 15, Loss: 1.6501, Accuracy: 0.9900
Epoch 16, Loss: 1.4761, Accuracy: 0.9800
Epoch 17, Loss: 1.5623, Accuracy: 0.9900
Epoch 18, Loss: 1.3813, Accuracy: 0.9800
Epoch 19, Loss: 1.3362, Accuracy: 0.9800
Epoch 20, Loss: 1.0961, Accuracy: 0.9800


In [32]:
print("Training complete.")

Training complete.


In [33]:
print("Training complete.")

Training complete.
